"""add image_path

Revision ID: 8d986edf6147
Revises: 
Create Date: 2026-05-26 12:27:08.006402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '8d986edf6147'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    return
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_chunks_subject_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_table('academic_documents')
    op.drop_table('generation_jobs')
    op.drop_index(op.f('ix_question_generation_profiles_subject_id'), table_name='question_generation_profiles')
    op.drop_table('question_generation_profiles')
    op.drop_index(op.f('ix_subject_syllabi_subject_id'), table_name='subject_syllabi')
    op.drop_table('subject_syllabi')
    op.alter_column('questions', 'image_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('questions', 'embedding_vector',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    return
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'embedding_vector',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('questions', 'image_path',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_table('subject_syllabi',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subject_id', sa.INTEGER(), nullable=False),
    sa.Column('syllabus_text', sa.TEXT(), nullable=True),
    sa.Column('modules_json', sqlite.JSON(), nullable=True),
    sa.Column('co_json', sqlite.JSON(), nullable=True),
    sa.Column('rbt_rules', sqlite.JSON(), nullable=True),
    sa.Column('uploaded_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_syllabi_subject_id'), 'subject_syllabi', ['subject_id'], unique=1)
    op.create_table('question_generation_profiles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subject_id', sa.INTEGER(), nullable=False),
    sa.Column('use_notes', sa.BOOLEAN(), nullable=False),
    sa.Column('use_question_bank', sa.BOOLEAN(), nullable=False),
    sa.Column('use_previous_papers', sa.BOOLEAN(), nullable=False),
    sa.Column('use_syllabus', sa.BOOLEAN(), nullable=False),
    sa.Column('strict_vtu_mode', sa.BOOLEAN(), nullable=False),
    sa.Column('strict_syllabus_mode', sa.BOOLEAN(), nullable=False),
    sa.Column('creativity_level', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_generation_profiles_subject_id'), 'question_generation_profiles', ['subject_id'], unique=1)
    op.create_table('generation_jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subject_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), nullable=False),
    sa.Column('progress', sa.INTEGER(), nullable=False),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('request_params', sqlite.JSON(), nullable=False),
    sa.Column('result_data', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('academic_documents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subject_id', sa.INTEGER(), nullable=False),
    sa.Column('uploaded_by', sa.INTEGER(), nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=500), nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('document_type', sa.VARCHAR(length=14), nullable=False),
    sa.Column('storage_path', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('processing_status', sa.VARCHAR(length=10), nullable=False),
    sa.Column('processing_error', sa.TEXT(), nullable=True),
    sa.Column('extracted_text', sa.TEXT(), nullable=True),
    sa.Column('page_count', sa.INTEGER(), nullable=True),
    sa.Column('total_chunks', sa.INTEGER(), nullable=False),
    sa.Column('structured_content', sqlite.JSON(), nullable=True),
    sa.Column('has_equations', sa.BOOLEAN(), nullable=False),
    sa.Column('has_figures', sa.BOOLEAN(), nullable=False),
    sa.Column('has_tables', sa.BOOLEAN(), nullable=False),
    sa.Column('equation_count', sa.INTEGER(), nullable=False),
    sa.Column('figure_count', sa.INTEGER(), nullable=False),
    sa.Column('table_count', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('document_id', sa.INTEGER(), nullable=False),
    sa.Column('subject_id', sa.INTEGER(), nullable=False),
    sa.Column('chunk_text', sa.TEXT(), nullable=False),
    sa.Column('chunk_summary', sa.TEXT(), nullable=True),
    sa.Column('chunk_index', sa.INTEGER(), nullable=False),
    sa.Column('token_count', sa.INTEGER(), nullable=False),
    sa.Column('module_number', sa.INTEGER(), nullable=True),
    sa.Column('syllabus_unit', sa.VARCHAR(length=200), nullable=True),
    sa.Column('topic_name', sa.VARCHAR(length=500), nullable=True),
    sa.Column('bloom_level', sa.VARCHAR(length=10), nullable=True),
    sa.Column('co_mapping', sa.VARCHAR(length=20), nullable=True),
    sa.Column('embedding_vector', sqlite.JSON(), nullable=True),
    sa.Column('page_number', sa.INTEGER(), nullable=True),
    sa.Column('confidence_score', sa.FLOAT(), nullable=False),
    sa.Column('approval_status', sa.VARCHAR(length=14), nullable=False),
    sa.Column('reviewed_by', sa.INTEGER(), nullable=True),
    sa.Column('review_notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['academic_documents.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_subject_id'), 'knowledge_chunks', ['subject_id'], unique=False)
    # ### end Alembic commands ###
